disabled_rules:
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - overridden_super_call
line_length: 220
identifier_name:
  min_length: 2
excluded:
  - BookNookTests
  - BookNookUITests
  - .build
